version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: crm_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build: ./backend
    image: ghcr.io/nurdev06/crm-cloud-backend:latest
    container_name: crm_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql+asyncpg://crmuser:crmpassword@db:5432/crmdb
      - DATABASE_URL_SYNC=postgresql://crmuser:crmpassword@db:5432/crmdb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    image: ghcr.io/nurdev06/crm-cloud-frontend:latest
    container_name: crm_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata:
